name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - practica-01
  pull_request:
    branches:
      - main
      - practica-01

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo Testing Stage
        run: echo "Testing Stage"
      - name: Upload Coverage and Report
        run: |
          echo "Uploading artifacts"
          mkdir -p artifacts
          echo "coverage.xml content" > artifacts/coverage.xml
          echo "report.xml content" > artifacts/report.xml
        # GitHub Actions no tiene un equivalente directo para "artifacts" de GitLab,
        # pero puedes usar `actions/upload-artifact` para almacenar archivos temporalmente.
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: artifacts/

  quality:
    name: SonarQube Quality Check
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SonarQube Analysis
        run: echo "Ejecutando SonarQube"

  build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}

  scanning:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@v0.2.0
        with:
          image-ref: ${{ secrets.DOCKER_REGISTRY }}/${{ github.repository }}:${{ github.sha }}
      - name: Upload Scanning Report
        uses: actions/upload-artifact@v3
        with:
          name: scanning-report
          path: scanning-report.json

  summary:
    name: Summary and Pages
    runs-on: ubuntu-latest
    needs: [testing, scanning]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate Summary Page
        run: |
          mkdir -p public
          echo "<html><body><h1>Hola Mundo</h1></body></html>" > public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public